#!/bin/bash
# Setup NRG Minotaur script

cat << EOF 

####################################
      UW_NRG Minotaur Setup 
####################################
EOF

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

fancy_echo "hello there...." "$1"
# Check to see if homebrew is installed
# curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install'

# Install Python 2.7
#brew install python
# Install pip 
#python get-pip.py

# Install pyserial, pygtk, numpy
#sudo pip install pyserial
#sudo pip install numpy
#brew install pygtk

#brew tap homebrew/science
#brew install opencv

#export PATH=$PATH:/usr/local/lib/python2.7/site-packages
